### ISSUE TITLE
Jupyter editor does not use sos codemirror mode

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-extension#2]
We have created a fake sos codemirror mode, which is basically a ipython codemirror mode. It is used for SoS notebook, but not for text editor that edits `.sos` files. Note that we have already [registered `.sos` file type](https://github.com/vatlab/sos-extension/blob/master/src/index.ts#L14) with appropriate mime type and extension. We will have to figure out how Jupyter editor detects filetype and  codemirror mode.

Note in the following figures the sos icon, but non-highlighted editor, and the highlighted code in sos notebook

![image](https://user-images.githubusercontent.com/9889312/37716559-cd11bfa4-2cec-11e8-8d66-2f8cc284f18d.png)
![image](https://user-images.githubusercontent.com/9889312/37716624-ef9f0efa-2cec-11e8-95dd-ef2eb50bebe4.png)

**Comment by gaow** [comment]
Sorry I'm a bit confused what this repo does, and how all these new developments are too applied to `sos-notebook` repo and work with Jupyter Notebook. At least it seems like one system uses `JS` and the other `TS`. Does it mean for some features maybe extension for both platforms will work, but for many features we'll have different implementations for `Jupyter Lab` and `Jupyter Notebook`?

**Comment by BoPeng** [comment]
This is for Jupyter lab. You need to run build.sh and then Jupyter lab.

**Comment by BoPeng** [comment]
You will also need to first upgrade `jupyterlab` with command

```
conda install  -c conda-forge jupyterlab
```

**Comment by BoPeng** [comment]
Solved. https://github.com/jupyterlab/jupyterlab/issues/4227
